name: CI - History

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      workdir: history

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
        working-directory: ${{env.workdir}}

      - name: Build app
        run: npm run build
        working-directory: ${{env.workdir}}

      - name: List artifacts
        run: ls -la ./dist
        working-directory: ${{env.workdir}}

      - name: Prepare artifacts
        working-directory: ${{env.workdir}}
        run: |
          mv dist/js/* dist/
          rm -rf dist/index.html dist/favicon.ico

      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-central-1'
          SOURCE_DIR: 'history/dist'
          DEST_DIR: 'history'
