name: CI - Nav

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      workdir: nav
    
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
        working-directory: ${{env.workdir}}

      - name: Build app
        run: npm run build
        working-directory: ${{env.workdir}}

      - name: List artifacts
        run: ls -la ./public/build
        working-directory: ${{env.workdir}}

      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-central-1'
          SOURCE_DIR: 'nav/public/build'
          DEST_DIR: 'nav'
